/*
    Copyright © 2019-2025 Perpetual Intelligence L.L.C. All rights reserved.

    For license, terms, and data policies, go to:
    https://terms.perpetualintelligence.com/articles/intro.html
*/

using System.Collections.Generic;
using System.IO;
using System.Text.Json.Serialization;
using OneImlx.Terminal.Commands.Routers;

namespace OneImlx.Terminal.Runtime
{
    /// <summary>
    /// A response generated by a <see cref="TerminalRequest"/>.
    /// </summary>
    public sealed class TerminalResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TerminalResponse"/> class.
        /// </summary>
        /// <param name="count">The number of requests.</param>
        /// <param name="batchId">The batch identifier.</param>
        public TerminalResponse(int count, string? batchId)
        {
            Requests = new TerminalRequest[count];
            Results = new object[count];
            BatchId = batchId;
        }

        /// <summary>
        /// The batch identifier.[]= i like it
        /// </summary>
        public string? BatchId { get; }

        /// <summary>
        /// The terminal requests.
        /// </summary>
        public TerminalRequest[] Requests { get; }

        /// <summary>
        /// The command router results.
        /// </summary>
        public object?[] Results { get; }
    }
}
