name: 'push-package'
description: 'Build, test, pack and publish a package'
inputs:
  project: 
    description: 'The project file name with src and test structure'
    required: true
  skiptest:
    description: 'The project does not have a test project'
    default: 'false'
    required: false
  config:
    description: 'The build configuration (Build or Release)'
    default: Release
    required: true
  version:
    description: 'The package version'
    required: true
  ghapikey:
    description: 'The Git Hub Api Key for package feed'
    required: true
  nugetapikey:
    description: 'The Nuget Api Key for package feed'
    required: true
  registry:
    description: 'The package registry (github or nuget)'
    default: github
    required: true
runs:
  using: "composite"
  steps:

    # Build
    - name: Build
      run: dotnet build ./src/${{ inputs.project }}/${{ inputs.project }}.csproj -c ${{ inputs.config }} --verbosity minimal
      shell: bash
      
    # Test
    - name: Test
      if: ${{ inputs.skiptest == 'false' }}
      run: dotnet test ./test/${{ inputs.project }}.Test/${{ inputs.project }}.Test.csproj -c ${{ inputs.config }} --verbosity minimal
      shell: bash

    # Pack
    - name: Pack
      run: |
        echo branch=${{ github.ref_name }} version=${{ inputs.version }}
        dotnet pack ./src/${{ inputs.project }}/${{ inputs.project }}.csproj -p:PackageVersion=${{ inputs.version }} --no-build -c ${{ inputs.config }} -o _packages -v minimal
      shell: bash

    # GITHUB
    - name: Github Push
      if: ${{ inputs.registry == 'github' }}
      run: dotnet nuget push _packages/PerpetualIntelligence.${{ inputs.project }}.${{ inputs.version }}.nupkg --skip-duplicate --no-symbols --api-key ${{ inputs.ghapikey }} --source github
      shell: bash    

    # NUGET - 1
    # First push to github (for package cadence, Nuget requires package verification)
    - name: Github Push
      if: ${{ inputs.registry == 'nuget' }}
      run: dotnet nuget push _packages/PerpetualIntelligence.${{ inputs.project }}.${{ inputs.version }}.nupkg --skip-duplicate --no-symbols --api-key ${{ inputs.ghapikey }} --source github
      shell: bash      
      
    # NUGET - 2
    # Second push to Nuget (for package cadence, Github will be used and in production Nuget after package verification)
    - name: Nuget Push
      if: ${{ inputs.registry == 'nuget' }}
      run: dotnet nuget push _packages/PerpetualIntelligence.${{ inputs.project }}.${{ inputs.version }}.nupkg --skip-duplicate --no-symbols --api-key ${{ inputs.nugetapikey }} --source nuget.org
      shell: bash
